### ISSUE TITLE
Option to enable fixed columns

### ISSUE THREAD

**Issue by Krokador** [lsgs/redcap-dag-switcher#5]
In the source of the module (dag_user_config.js, line 34), the fixed column has been commented out, with no way of changing it. I saw firsthand that, indeed, when sorting, the zebra rows don't follow, but that's a visual gripe and not really a functional issue. It would be nice if we could choose to enable the fixed columns anyway in the module configuration.

We have a project with 130+ DAGs and over 800 users. Not having the fixed column makes this impossible to use (I changed it manually, but whenever we update we need to go back and change the setting again). It doesn't have to be pretty, just usable.

I mean, the user rights and dag pages are very hard to use to begin with because we've had to create up to 8 accounts per user before we found this module, but we'd like to limit the number of additional accounts moving forward!

**Comment by lsgs** [comment]
Thanks @Krokador I had another look at that and found it's behaving a little better now. There is one other CSS tweak I made to get rid of an additional unnecessary scroll-bar and it works well now. Still get the colouring on the left column tables rows when it's sorted by another column, but (as you say) that's only cosmetic and no big deal. I've done a new release as v1.2.4.
