### ISSUE TITLE
getUserDAGs() does not take into account redcap_log_event2-5

### ISSUE THREAD

**Issue by dwrogers** [lsgs/redcap-dag-switcher#6]
getUserDAGs() does not take into account redcap_log_event2-5.

**Comment by lsgs** [comment]
Thanks for the prompt @dwrogers. I've made a few changes to the module and done a new release. The check for config settings in the redcap_log_event table is a legacy from the early versions of the module and is no longer required. As you say, it would need re-writing to account for the new log tables so I have just removed it.
