### ISSUE TITLE
Bug: usernames with mixture of upper/lower case letters prevent DAG Switcher appearing

### ISSUE THREAD

**Issue by jeromibload** [lsgs/redcap-dag-switcher#7]
The DAG switcher only works if usernames are first lowercased before they're added onto the REDCap project it's installed on.

For instance. I added a user onto my new REDCap project whose existing REDCap username*** was DoeJohnR (name changed to protect the innocent)
So I added it in the same case - DoeJohnR
Even though I set them up to use the DAG Switcher, it didn't appear.
After checking every conceivable thing in the universe that might be causing this except for the thing that was actually causing it, I tried removing them from the project and readding them as doejohnr. And hey presto the DAG Switcher appeared.
So I can only guess that somewhere in the DAG Switcher it's doing a comparison where on username and not lowercasing it. Or something similar.
I hope this helps locate the bug.
David.

*** personally, I wouldn't add a username with anything but lowercase letters - but these usernames on the user whitelist were originally created by our IT Services guys back when the user joined the organisation, so it's beyond my control. By the time it got to me, she's already been using REDCap on other projects for a while. But I imagine mixed case usernames are not that common in reality.

**Comment by lsgs** [comment]
Thanks for the report @jeromibload. Unfortunately I have not been able to replicate the problem. I did make some fixes for mixed-case usernames in [version 1.2.2](https://github.com/lsgs/redcap-dag-switcher/releases/tag/1.2.2). Could it be that you were still using a version before that?
