### ISSUE TITLE
DAG Switcher Disabled for large number of users or DAGs

### ISSUE THREAD

**Issue by garyking1988** [lsgs/redcap-dag-switcher#8]
Hi,
I have encountered the limitation within your module "when there are a large number of users and/or DAGs in the project (if Users X DAGs > 10,000), so the DAG Switcher has been disabled in this project."

Can you tell me if there is anyway around this limitation or if there are plans to increase the limit in an future releases, if there are any planned?

I'm running in REDCap 10.0.21, which I've also just discovered is unsupported by your module.

Many thanks,
Gary

**Comment by lsgs** [comment]
Yes Gary, the DAG Switcher external module became integrated into core REDCa at around v10.0 or v10.1 so is no longer supported. The core code implemented the module's enhancements for >10k user/DAG combinations in 10.2.3. I strongly encourage you to upgrade to a recent version.
