### ISSUE TITLE
Merged with REDCap?

### ISSUE THREAD

**Issue by mmcev106** [lsgs/redcap-dag-switcher#9]
@lsgs, Luke does REDCap's built-in DAG switching functionality completely replace this module, or is there a reason why someone might still want to use this module on new projects?

**Comment by lsgs** [comment]
It does, @mmcev106. There was a period where the built-in functionality was catching up to the EM - handling large numbers of users & DAGs, the API method - but these days there is no reason to use the EM.

**Comment by mmcev106** [comment]
Thanks!  I just edited the description for the last submission in the repo, and added bolded sentence:
![image](https://github.com/lsgs/redcap-dag-switcher/assets/2627854/2e7b9017-cdb9-45b4-9eef-686b4c698227)
